plugins {
  id 'application'
}

application {
  mainClass = 'org.demoth.cake.enginetools.BitmapFontGeneratorTool'
  applicationDefaultJvmArgs = ['--enable-native-access=ALL-UNNAMED']
}

dependencies {
  implementation libs.gdx
  implementation libs.gdxFreetype
  implementation libs.gdxTools
  runtimeOnly(libs.gdxPlatform) {
    artifact {
      classifier = 'natives-desktop'
    }
  }
  runtimeOnly(libs.gdxFreetypePlatform) {
    artifact {
      classifier = 'natives-desktop'
    }
  }
}
