plugins {
  alias(libs.plugins.kotlinJvm) apply false
  alias(libs.plugins.kotlinSerialization) apply false
  alias(libs.plugins.gitProperties) apply false
}

subprojects {
  apply plugin: 'java-library'
  apply plugin: 'org.jetbrains.kotlin.jvm'
  apply plugin: 'jacoco'

  group = 'org.demoth'
  version = '1.2.0'
  ext.appName = 'cake'

  kotlin {
    jvmToolchain(21)
  }

  dependencies {
    testImplementation(rootProject.libs.junitJupiterApi)
    testImplementation(rootProject.libs.junitJupiterParams)
    testRuntimeOnly(rootProject.libs.junitPlatformLauncher)
    testRuntimeOnly(rootProject.libs.junitJupiterEngine)
  }

  tasks.withType(Test).configureEach {
    useJUnitPlatform()
    finalizedBy(tasks.named('jacocoTestReport'))
  }

  tasks.withType(JacocoReport).configureEach {
    dependsOn(tasks.withType(Test))

    reports {
      xml.required = true
      html.required = true
      csv.required = false
    }
  }
}
