rootProject.name = "jake2"
include (":qcommon")
include (":game")
include (":server")
//include (":client")
include (":dedicated")
//include (":fullgame")
include (":maptools")
include (":cake")
include (":cake:core")
include (":cake:lwjgl3")
include (":cake:engine-tools")
