package org.demoth.cake.profile

import jake2.qcommon.exec.Cvar
import jake2.qcommon.vfs.DefaultWritableFileSystem
import jake2.qcommon.vfs.VfsOpenOptions
import jake2.qcommon.vfs.VfsWriteOptions
import jake2.qcommon.vfs.WritableFileSystem
import java.nio.charset.StandardCharsets
import java.nio.file.Path

class CakeProfileConfigStore(
    private val writableFactory: (String) -> WritableFileSystem = { profileId ->
        val home = Path.of(System.getProperty("user.home"))
        DefaultWritableFileSystem(home.resolve(".cake").resolve(profileId))
    },
    private val appendArchiveVariables: (String) -> Unit = { path ->
        Cvar.getInstance().writeArchiveVariables(path)
    },
) {
    fun readConfig(profileId: String): String? {
        val writable = writableFactory(profileId)
        val opened = writable.openReadReal(CONFIG_FILE_NAME, VfsOpenOptions.DEFAULT)
        if (!opened.success || opened.value == null) {
            return null
        }
        opened.value.use { handle ->
            handle.inputStream().use { input ->
                return input.readBytes().toString(StandardCharsets.UTF_8)
            }
        }
    }

    fun writeConfig(
        profileId: String,
        bindings: List<Pair<String, String>>,
    ): String {
        val writable = writableFactory(profileId)
        val opened = writable.openWrite(CONFIG_FILE_NAME, VfsWriteOptions.TRUNCATE)
        require(opened.success && opened.value != null) { "Failed to open profile config for write" }

        opened.value.use { handle ->
            handle.outputStream().use { output ->
                output.write(HEADER_LINE.toByteArray(StandardCharsets.UTF_8))
                output.write("unbindall\n".toByteArray(StandardCharsets.UTF_8))
                for ((key, binding) in bindings) {
                    val escapedBinding = binding
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                    output.write("bind $key \"$escapedBinding\"\n".toByteArray(StandardCharsets.UTF_8))
                }
            }
        }

        val path = writable.resolveWritePath(CONFIG_FILE_NAME)
            ?: throw IllegalStateException("Failed to resolve profile config path")
        appendArchiveVariables(path)
        return path
    }

    companion object {
        const val CONFIG_FILE_NAME: String = "config.cfg"
        private const val HEADER_LINE: String =
            "// generated by Cake profile config, not a full legacy config.cfg reimplementation\n"
    }
}
