package org.demoth.cake.profile

import jake2.qcommon.vfs.DefaultWritableFileSystem
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path

class CakeProfileConfigStoreTest {
    @TempDir
    lateinit var temp: Path

    @Test
    fun readConfigReturnsNullWhenMissing() {
        val store = CakeProfileConfigStore(
            writableFactory = { profileId -> DefaultWritableFileSystem(temp.resolve(profileId)) },
            appendArchiveVariables = {},
        )

        assertNull(store.readConfig("default"))
    }

    @Test
    fun writeConfigSerializesBindingsAndArchiveSection() {
        val store = CakeProfileConfigStore(
            writableFactory = { profileId -> DefaultWritableFileSystem(temp.resolve(profileId)) },
            appendArchiveVariables = { path ->
                Files.writeString(Path.of(path), "set name \"marine\"\n", Charsets.UTF_8, java.nio.file.StandardOpenOption.APPEND)
            },
        )

        val writtenPath = store.writeConfig(
            profileId = "marine",
            bindings = listOf(
                "W" to "+forward",
                "MOUSE1" to "say \"hi\"",
            ),
        )

        val text = Files.readString(Path.of(writtenPath))
        assertTrue(text.contains("generated by Cake profile config"))
        assertTrue(text.contains("unbindall"))
        assertTrue(text.contains("bind W \"+forward\""))
        assertTrue(text.contains("bind MOUSE1 \"say \\\"hi\\\"\""))
        assertTrue(text.contains("set name \"marine\""))
    }

    @Test
    fun readConfigReturnsWrittenContents() {
        val store = CakeProfileConfigStore(
            writableFactory = { profileId -> DefaultWritableFileSystem(temp.resolve(profileId)) },
            appendArchiveVariables = {},
        )

        store.writeConfig(
            profileId = "default",
            bindings = listOf("W" to "+forward"),
        )

        val text = store.readConfig("default")
        requireNotNull(text)
        assertEquals(
            """
            // generated by Cake profile config; not a full legacy config.cfg reimplementation
            unbindall
            bind W "+forward"
            """.trimIndent() + "\n",
            text,
        )
    }
}
