/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

// Created on 13.11.2003 by RST.
// $Id: M_Float.java,v 1.5 2003-11-29 13:28:28 rst Exp $

package jake2.game;

public class M_Float extends Game {

	//	This file generated by ModelGen - Do NOT Modify

	public final static int FRAME_actvat01= 0;
	public final static int FRAME_actvat02= 1;
	public final static int FRAME_actvat03= 2;
	public final static int FRAME_actvat04= 3;
	public final static int FRAME_actvat05= 4;
	public final static int FRAME_actvat06= 5;
	public final static int FRAME_actvat07= 6;
	public final static int FRAME_actvat08= 7;
	public final static int FRAME_actvat09= 8;
	public final static int FRAME_actvat10= 9;
	public final static int FRAME_actvat11= 10;
	public final static int FRAME_actvat12= 11;
	public final static int FRAME_actvat13= 12;
	public final static int FRAME_actvat14= 13;
	public final static int FRAME_actvat15= 14;
	public final static int FRAME_actvat16= 15;
	public final static int FRAME_actvat17= 16;
	public final static int FRAME_actvat18= 17;
	public final static int FRAME_actvat19= 18;
	public final static int FRAME_actvat20= 19;
	public final static int FRAME_actvat21= 20;
	public final static int FRAME_actvat22= 21;
	public final static int FRAME_actvat23= 22;
	public final static int FRAME_actvat24= 23;
	public final static int FRAME_actvat25= 24;
	public final static int FRAME_actvat26= 25;
	public final static int FRAME_actvat27= 26;
	public final static int FRAME_actvat28= 27;
	public final static int FRAME_actvat29= 28;
	public final static int FRAME_actvat30= 29;
	public final static int FRAME_actvat31= 30;
	public final static int FRAME_attak101= 31;
	public final static int FRAME_attak102= 32;
	public final static int FRAME_attak103= 33;
	public final static int FRAME_attak104= 34;
	public final static int FRAME_attak105= 35;
	public final static int FRAME_attak106= 36;
	public final static int FRAME_attak107= 37;
	public final static int FRAME_attak108= 38;
	public final static int FRAME_attak109= 39;
	public final static int FRAME_attak110= 40;
	public final static int FRAME_attak111= 41;
	public final static int FRAME_attak112= 42;
	public final static int FRAME_attak113= 43;
	public final static int FRAME_attak114= 44;
	public final static int FRAME_attak201= 45;
	public final static int FRAME_attak202= 46;
	public final static int FRAME_attak203= 47;
	public final static int FRAME_attak204= 48;
	public final static int FRAME_attak205= 49;
	public final static int FRAME_attak206= 50;
	public final static int FRAME_attak207= 51;
	public final static int FRAME_attak208= 52;
	public final static int FRAME_attak209= 53;
	public final static int FRAME_attak210= 54;
	public final static int FRAME_attak211= 55;
	public final static int FRAME_attak212= 56;
	public final static int FRAME_attak213= 57;
	public final static int FRAME_attak214= 58;
	public final static int FRAME_attak215= 59;
	public final static int FRAME_attak216= 60;
	public final static int FRAME_attak217= 61;
	public final static int FRAME_attak218= 62;
	public final static int FRAME_attak219= 63;
	public final static int FRAME_attak220= 64;
	public final static int FRAME_attak221= 65;
	public final static int FRAME_attak222= 66;
	public final static int FRAME_attak223= 67;
	public final static int FRAME_attak224= 68;
	public final static int FRAME_attak225= 69;
	public final static int FRAME_attak301= 70;
	public final static int FRAME_attak302= 71;
	public final static int FRAME_attak303= 72;
	public final static int FRAME_attak304= 73;
	public final static int FRAME_attak305= 74;
	public final static int FRAME_attak306= 75;
	public final static int FRAME_attak307= 76;
	public final static int FRAME_attak308= 77;
	public final static int FRAME_attak309= 78;
	public final static int FRAME_attak310= 79;
	public final static int FRAME_attak311= 80;
	public final static int FRAME_attak312= 81;
	public final static int FRAME_attak313= 82;
	public final static int FRAME_attak314= 83;
	public final static int FRAME_attak315= 84;
	public final static int FRAME_attak316= 85;
	public final static int FRAME_attak317= 86;
	public final static int FRAME_attak318= 87;
	public final static int FRAME_attak319= 88;
	public final static int FRAME_attak320= 89;
	public final static int FRAME_attak321= 90;
	public final static int FRAME_attak322= 91;
	public final static int FRAME_attak323= 92;
	public final static int FRAME_attak324= 93;
	public final static int FRAME_attak325= 94;
	public final static int FRAME_attak326= 95;
	public final static int FRAME_attak327= 96;
	public final static int FRAME_attak328= 97;
	public final static int FRAME_attak329= 98;
	public final static int FRAME_attak330= 99;
	public final static int FRAME_attak331= 100;
	public final static int FRAME_attak332= 101;
	public final static int FRAME_attak333= 102;
	public final static int FRAME_attak334= 103;
	public final static int FRAME_death01= 104;
	public final static int FRAME_death02= 105;
	public final static int FRAME_death03= 106;
	public final static int FRAME_death04= 107;
	public final static int FRAME_death05= 108;
	public final static int FRAME_death06= 109;
	public final static int FRAME_death07= 110;
	public final static int FRAME_death08= 111;
	public final static int FRAME_death09= 112;
	public final static int FRAME_death10= 113;
	public final static int FRAME_death11= 114;
	public final static int FRAME_death12= 115;
	public final static int FRAME_death13= 116;
	public final static int FRAME_pain101= 117;
	public final static int FRAME_pain102= 118;
	public final static int FRAME_pain103= 119;
	public final static int FRAME_pain104= 120;
	public final static int FRAME_pain105= 121;
	public final static int FRAME_pain106= 122;
	public final static int FRAME_pain107= 123;
	public final static int FRAME_pain201= 124;
	public final static int FRAME_pain202= 125;
	public final static int FRAME_pain203= 126;
	public final static int FRAME_pain204= 127;
	public final static int FRAME_pain205= 128;
	public final static int FRAME_pain206= 129;
	public final static int FRAME_pain207= 130;
	public final static int FRAME_pain208= 131;
	public final static int FRAME_pain301= 132;
	public final static int FRAME_pain302= 133;
	public final static int FRAME_pain303= 134;
	public final static int FRAME_pain304= 135;
	public final static int FRAME_pain305= 136;
	public final static int FRAME_pain306= 137;
	public final static int FRAME_pain307= 138;
	public final static int FRAME_pain308= 139;
	public final static int FRAME_pain309= 140;
	public final static int FRAME_pain310= 141;
	public final static int FRAME_pain311= 142;
	public final static int FRAME_pain312= 143;
	public final static int FRAME_stand101= 144;
	public final static int FRAME_stand102= 145;
	public final static int FRAME_stand103= 146;
	public final static int FRAME_stand104= 147;
	public final static int FRAME_stand105= 148;
	public final static int FRAME_stand106= 149;
	public final static int FRAME_stand107= 150;
	public final static int FRAME_stand108= 151;
	public final static int FRAME_stand109= 152;
	public final static int FRAME_stand110= 153;
	public final static int FRAME_stand111= 154;
	public final static int FRAME_stand112= 155;
	public final static int FRAME_stand113= 156;
	public final static int FRAME_stand114= 157;
	public final static int FRAME_stand115= 158;
	public final static int FRAME_stand116= 159;
	public final static int FRAME_stand117= 160;
	public final static int FRAME_stand118= 161;
	public final static int FRAME_stand119= 162;
	public final static int FRAME_stand120= 163;
	public final static int FRAME_stand121= 164;
	public final static int FRAME_stand122= 165;
	public final static int FRAME_stand123= 166;
	public final static int FRAME_stand124= 167;
	public final static int FRAME_stand125= 168;
	public final static int FRAME_stand126= 169;
	public final static int FRAME_stand127= 170;
	public final static int FRAME_stand128= 171;
	public final static int FRAME_stand129= 172;
	public final static int FRAME_stand130= 173;
	public final static int FRAME_stand131= 174;
	public final static int FRAME_stand132= 175;
	public final static int FRAME_stand133= 176;
	public final static int FRAME_stand134= 177;
	public final static int FRAME_stand135= 178;
	public final static int FRAME_stand136= 179;
	public final static int FRAME_stand137= 180;
	public final static int FRAME_stand138= 181;
	public final static int FRAME_stand139= 182;
	public final static int FRAME_stand140= 183;
	public final static int FRAME_stand141= 184;
	public final static int FRAME_stand142= 185;
	public final static int FRAME_stand143= 186;
	public final static int FRAME_stand144= 187;
	public final static int FRAME_stand145= 188;
	public final static int FRAME_stand146= 189;
	public final static int FRAME_stand147= 190;
	public final static int FRAME_stand148= 191;
	public final static int FRAME_stand149= 192;
	public final static int FRAME_stand150= 193;
	public final static int FRAME_stand151= 194;
	public final static int FRAME_stand152= 195;
	public final static int FRAME_stand201= 196;
	public final static int FRAME_stand202= 197;
	public final static int FRAME_stand203= 198;
	public final static int FRAME_stand204= 199;
	public final static int FRAME_stand205= 200;
	public final static int FRAME_stand206= 201;
	public final static int FRAME_stand207= 202;
	public final static int FRAME_stand208= 203;
	public final static int FRAME_stand209= 204;
	public final static int FRAME_stand210= 205;
	public final static int FRAME_stand211= 206;
	public final static int FRAME_stand212= 207;
	public final static int FRAME_stand213= 208;
	public final static int FRAME_stand214= 209;
	public final static int FRAME_stand215= 210;
	public final static int FRAME_stand216= 211;
	public final static int FRAME_stand217= 212;
	public final static int FRAME_stand218= 213;
	public final static int FRAME_stand219= 214;
	public final static int FRAME_stand220= 215;
	public final static int FRAME_stand221= 216;
	public final static int FRAME_stand222= 217;
	public final static int FRAME_stand223= 218;
	public final static int FRAME_stand224= 219;
	public final static int FRAME_stand225= 220;
	public final static int FRAME_stand226= 221;
	public final static int FRAME_stand227= 222;
	public final static int FRAME_stand228= 223;
	public final static int FRAME_stand229= 224;
	public final static int FRAME_stand230= 225;
	public final static int FRAME_stand231= 226;
	public final static int FRAME_stand232= 227;
	public final static int FRAME_stand233= 228;
	public final static int FRAME_stand234= 229;
	public final static int FRAME_stand235= 230;
	public final static int FRAME_stand236= 231;
	public final static int FRAME_stand237= 232;
	public final static int FRAME_stand238= 233;
	public final static int FRAME_stand239= 234;
	public final static int FRAME_stand240= 235;
	public final static int FRAME_stand241= 236;
	public final static int FRAME_stand242= 237;
	public final static int FRAME_stand243= 238;
	public final static int FRAME_stand244= 239;
	public final static int FRAME_stand245= 240;
	public final static int FRAME_stand246= 241;
	public final static int FRAME_stand247= 242;
	public final static int FRAME_stand248= 243;
	public final static int FRAME_stand249= 244;
	public final static int FRAME_stand250= 245;
	public final static int FRAME_stand251= 246;
	public final static int FRAME_stand252= 247;

	public final static float MODEL_SCALE= 1.000000f;

	static int sound_attack2;
	static int sound_attack3;
	static int sound_death1;
	static int sound_idle;
	static int sound_pain1;
	static int sound_pain2;
	static int sound_sight;

	static EntInteractAdapter floater_sight= new EntInteractAdapter() {
		public boolean interact(edict_t self, edict_t other) {
			gi.sound(self, CHAN_VOICE, sound_sight, 1, ATTN_NORM, 0);
			return true;
		}
	};

	static EntThinkAdapter floater_idle= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			gi.sound(self, CHAN_VOICE, sound_idle, 1, ATTN_IDLE, 0);
			return true;
		}
	};

	static EntThinkAdapter floater_fire_blaster= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			float[] start={0,0,0};
			float[] forward={0,0,0}, right={0,0,0};
			float[] end={0,0,0};
			float[] dir={0,0,0};
			int effect;

			if ((self.s.frame == FRAME_attak104)
				|| (self.s.frame == FRAME_attak107))
				effect= EF_HYPERBLASTER;
			else
				effect= 0;
			AngleVectors(self.s.angles, forward, right, null);
			G_ProjectSource(
				self.s.origin,
				monster_flash_offset[MZ2_FLOAT_BLASTER_1],
				forward,
				right,
				start);

			VectorCopy(self.enemy.s.origin, end);
			end[2] += self.enemy.viewheight;
			VectorSubtract(end, start, dir);

			monster_fire_blaster(
				self,
				start,
				dir,
				1,
				1000,
				MZ2_FLOAT_BLASTER_1,
				effect);

			return true;
		}
	};

	static mframe_t floater_frames_stand1[]=
		new mframe_t[] {
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null)};
	static mmove_t floater_move_stand1=
		new mmove_t(
			FRAME_stand101,
			FRAME_stand152,
			floater_frames_stand1,
			null);

	static mframe_t floater_frames_stand2[]=
		new mframe_t[] {
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null),
			new mframe_t(ai_stand, 0, null)};
	static mmove_t floater_move_stand2=
		new mmove_t(
			FRAME_stand201,
			FRAME_stand252,
			floater_frames_stand2,
			null);

	static EntThinkAdapter floater_stand= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			if (random() <= 0.5)
				self.monsterinfo.currentmove= floater_move_stand1;
			else
				self.monsterinfo.currentmove= floater_move_stand2;
			return true;
		}
	};

	static mframe_t floater_frames_activate[]=
		new mframe_t[] {
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null)};

	static mmove_t floater_move_activate=
		new mmove_t(
			FRAME_actvat01,
			FRAME_actvat31,
			floater_frames_activate,
			null);

	static EntThinkAdapter floater_run= new EntThinkAdapter() {
		public boolean think(edict_t self) {

			if ((self.monsterinfo.aiflags & AI_STAND_GROUND) != 0)
				self.monsterinfo.currentmove= floater_move_stand1;
			else
				self.monsterinfo.currentmove= floater_move_run;

			return true;
		}
	};

	static mframe_t floater_frames_attack1[]=
		new mframe_t[] { new mframe_t(ai_charge, 0, null), // Blaster attack)
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
		// BOOM (0, -25.8, 32.5)	-- LOOP Starts
		new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, floater_fire_blaster),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null)
		// -- LOOP Ends
	};
	static mmove_t floater_move_attack1=
		new mmove_t(
			FRAME_attak101,
			FRAME_attak114,
			floater_frames_attack1,
			floater_run);

	static float[] aim= { MELEE_DISTANCE, 0, 0 };

	static EntThinkAdapter floater_wham= new EntThinkAdapter() {
		public boolean think(edict_t self) {

			gi.sound(self, CHAN_WEAPON, sound_attack3, 1, ATTN_NORM, 0);
			fire_hit(self, aim, 5 + rand() % 6, -50);
			return true;
		}
	};

	static mframe_t floater_frames_attack2[]=
		new mframe_t[] { new mframe_t(ai_charge, 0, null), // Claws
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, floater_wham),
		// WHAM (0, -45, 29.6)		-- LOOP Starts
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
		//							-- LOOP Ends
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null)};
	static mmove_t floater_move_attack2=
		new mmove_t(
			FRAME_attak201,
			FRAME_attak225,
			floater_frames_attack2,
			floater_run);

	static EntThinkAdapter floater_zap= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			float[] forward={0,0,0}, right={0,0,0};
			float[] origin={0,0,0};
			float[] dir={0,0,0};
			float[] offset={0,0,0};

			VectorSubtract(self.enemy.s.origin, self.s.origin, dir);

			AngleVectors(self.s.angles, forward, right, null);
			//FIXME use a flash and replace these two lines with the commented one
			VectorSet(offset, 18.5f, -0.9f, 10f);
			G_ProjectSource(self.s.origin, offset, forward, right, origin);
			//		G_ProjectSource (self.s.origin, monster_flash_offset[flash_number], forward, right, origin);

			gi.sound(self, CHAN_WEAPON, sound_attack2, 1, ATTN_NORM, 0);

			//FIXME use the flash, Luke
			gi.WriteByte(svc_temp_entity);
			gi.WriteByte(TE_SPLASH);
			gi.WriteByte(32);
			gi.WritePosition(origin);
			gi.WriteDir(dir);
			gi.WriteByte(1); //sparks
			gi.multicast(origin, MULTICAST_PVS);

			T_Damage(
				self.enemy,
				self,
				self,
				dir,
				self.enemy.s.origin,
				vec3_origin,
				5 + rand() % 6,
				-10,
				DAMAGE_ENERGY,
				MOD_UNKNOWN);
			return true;
		}
	};
	static mframe_t floater_frames_attack3[]=
		new mframe_t[] {
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, floater_zap),
		//								-- LOOP Starts
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
		//								-- LOOP Ends
		new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null),
			new mframe_t(ai_charge, 0, null)};

	static mmove_t floater_move_attack3=
		new mmove_t(
			FRAME_attak301,
			FRAME_attak334,
			floater_frames_attack3,
			floater_run);

	static mframe_t floater_frames_death[]=
		new mframe_t[] {
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null)};

	static EntThinkAdapter floater_dead= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			VectorSet(self.mins, -16, -16, -24);
			VectorSet(self.maxs, 16, 16, -8);
			self.movetype= MOVETYPE_TOSS;
			self.svflags |= SVF_DEADMONSTER;
			self.nextthink= 0;
			gi.linkentity(self);
			return true;
		}
	};

	static mmove_t floater_move_death=
		new mmove_t(
			FRAME_death01,
			FRAME_death13,
			floater_frames_death,
			floater_dead);

	static mframe_t floater_frames_pain1[]=
		new mframe_t[] {
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null)};

	static mmove_t floater_move_pain1=
		new mmove_t(
			FRAME_pain101,
			FRAME_pain107,
			floater_frames_pain1,
			floater_run);

	static mframe_t floater_frames_pain2[]=
		new mframe_t[] {
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null)};
	static mmove_t floater_move_pain2=
		new mmove_t(
			FRAME_pain201,
			FRAME_pain208,
			floater_frames_pain2,
			floater_run);

	static mframe_t floater_frames_pain3[]=
		new mframe_t[] {
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null),
			new mframe_t(ai_move, 0, null)};
	static mmove_t floater_move_pain3=
		new mmove_t(
			FRAME_pain301,
			FRAME_pain312,
			floater_frames_pain3,
			floater_run);

	static mframe_t floater_frames_walk[]=
		new mframe_t[] {
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null),
			new mframe_t(ai_walk, 5, null)};
	static mmove_t floater_move_walk=
		new mmove_t(FRAME_stand101, FRAME_stand152, floater_frames_walk, null);

	static mframe_t floater_frames_run[]=
		new mframe_t[] {
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null),
			new mframe_t(ai_run, 13, null)};
	static mmove_t floater_move_run=
		new mmove_t(FRAME_stand101, FRAME_stand152, floater_frames_run, null);

	static EntThinkAdapter floater_walk= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			self.monsterinfo.currentmove= floater_move_walk;
			return true;
		}
	};

	static EntThinkAdapter floater_attack= new EntThinkAdapter() {
		public boolean think(edict_t self) {
			self.monsterinfo.currentmove= floater_move_attack1;
			return true;
		}
	};

	static EntThinkAdapter floater_melee= new EntThinkAdapter() {
		public boolean think(edict_t self) {

			if (random() < 0.5)
				self.monsterinfo.currentmove= floater_move_attack3;
			else
				self.monsterinfo.currentmove= floater_move_attack2;
			return true;
		}
	};

	static EntPainAdapter floater_pain= new EntPainAdapter() {
		public void pain(edict_t self, edict_t other, float kick, int damage) {
			int n;

			if (self.health < (self.max_health / 2))
				self.s.skinnum= 1;

			if (level.time < self.pain_debounce_time)
				return;

			self.pain_debounce_time= level.time + 3;
			if (skill.value == 3)
				return; // no pain anims in nightmare

			n= (rand() + 1) % 3;
			if (n == 0) {
				gi.sound(self, CHAN_VOICE, sound_pain1, 1, ATTN_NORM, 0);
				self.monsterinfo.currentmove= floater_move_pain1;
			} else {
				gi.sound(self, CHAN_VOICE, sound_pain2, 1, ATTN_NORM, 0);
				self.monsterinfo.currentmove= floater_move_pain2;
			}
			return;
		}
	};

	static EntDieAdapter floater_die= new EntDieAdapter() {

		public void die(
			edict_t self,
			edict_t inflictor,
			edict_t attacker,
			int damage,
			float[] point) {
			gi.sound(self, CHAN_VOICE, sound_death1, 1, ATTN_NORM, 0);
			BecomeExplosion1(self);

		}
	};

	/*QUAKED monster_floater (1 .5 0) (-16 -16 -24) (16 16 32) Ambush Trigger_Spawn Sight
	*/
	static void SP_monster_floater(edict_t self) {
		if (deathmatch.value != 0) {
			G_FreeEdict(self);
			return;
		}

		sound_attack2= gi.soundindex("floater/fltatck2.wav");
		sound_attack3= gi.soundindex("floater/fltatck3.wav");
		sound_death1= gi.soundindex("floater/fltdeth1.wav");
		sound_idle= gi.soundindex("floater/fltidle1.wav");
		sound_pain1= gi.soundindex("floater/fltpain1.wav");
		sound_pain2= gi.soundindex("floater/fltpain2.wav");
		sound_sight= gi.soundindex("floater/fltsght1.wav");

		gi.soundindex("floater/fltatck1.wav");

		self.s.sound= gi.soundindex("floater/fltsrch1.wav");

		self.movetype= MOVETYPE_STEP;
		self.solid= SOLID_BBOX;
		self.s.modelindex= gi.modelindex("models/monsters/float/tris.md2");
		VectorSet(self.mins, -24, -24, -24);
		VectorSet(self.maxs, 24, 24, 32);

		self.health= 200;
		self.gib_health= -80;
		self.mass= 300;

		self.pain= floater_pain;
		self.die= floater_die;

		self.monsterinfo.stand= floater_stand;
		self.monsterinfo.walk= floater_walk;
		self.monsterinfo.run= floater_run;
		//		self.monsterinfo.dodge = floater_dodge;
		self.monsterinfo.attack= floater_attack;
		self.monsterinfo.melee= floater_melee;
		self.monsterinfo.sight= floater_sight;
		self.monsterinfo.idle= floater_idle;

		gi.linkentity(self);

		if (random() <= 0.5)
			self.monsterinfo.currentmove= floater_move_stand1;
		else
			self.monsterinfo.currentmove= floater_move_stand2;

		self.monsterinfo.scale= MODEL_SCALE;

		flymonster_start.think(self);
	}
}
