dependencies {
  implementation libs.gdxSvmhelperBackendLwjgl3
  implementation libs.gdxSvmhelperExtensionFreetype
}

def desktopAppName = 'cake-client'
graalvmNative {
  binaries {
    main {
      imageName = desktopAppName
      mainClass.set('org.demoth.cake.lwjgl3.Lwjgl3GameLauncher')
      requiredVersion = '25.0'
      buildArgs.add('--enable-native-access=ALL-UNNAMED')
      buildArgs.add("-H:+UnlockExperimentalVMOptions")
      buildArgs.addAll(
        '--exclude-config',
        '.*(gdx-svmhelper-backend-lwjgl3|cake-).*\\.jar',
        'META-INF/native-image/gdx-svmhelper/backend-lwjgl3/native-image.properties'
      )
      resources.autodetection {
        enabled = true
        restrictToProjectDependencies = false
      }
      buildArgs.add("--initialize-at-build-time=kotlin.DeprecationLevel")
      buildArgs.add("-march=compatibility")
      jvmArgs.addAll("-Dfile.encoding=UTF8")
      sharedLibrary = false
    }
  }
}
