package jake2.qcommon.exec;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static jake2.qcommon.exec.Cbuf.splitCommandLine;
import static jake2.qcommon.exec.Cbuf.splitScriptCommandLine;
import static org.junit.jupiter.api.Assertions.*;

public class CbufTest {
    @Test
    public void testSplit() {
        assertEquals(Arrays.asList("hello", "world"), splitCommandLine("hello;world"));
    }

    @Test
    public void testSplitInQuotes() {
        assertEquals(Arrays.asList("test", "hello;world"), splitCommandLine("test;\"hello;world\""));
    }

    @Test
    public void testNewLines() {
        assertEquals(Arrays.asList("1", "2", "3", "4"), splitCommandLine("1\n2\r3;4"));
    }

    @Test
    public void testSplitScriptStripsCommentBeforeSemicolonSplit() {
        assertEquals(
                Arrays.asList("bind w \"+forward\"", "set name marine"),
                splitScriptCommandLine(
                        "// generated by Cake profile config; not a full legacy config.cfg reimplementation\n" +
                                "bind w \"+forward\" // keep this binding; not another command\n" +
                                "set name marine"));
    }

    @Test
    public void testSplitScriptKeepsDoubleSlashInsideQuotes() {
        assertEquals(
                Arrays.asList("bind x \"say //still text\"", "echo done"),
                splitScriptCommandLine("bind x \"say //still text\"\necho done"));
    }
}
